In [ ]:
import numpy as np
import pandas as pd
from sklearn.feature_extraction.text import CountVectorizer
from sklearn.naive_bayes import MultinomialNB, GuassianNB
from sklearn.metrics import accuracy_score, classification_report

In [ ]:
df = pd.read_csv('/content/newsgroups_train.csv', on_bad_lines='skip')
df.head()

text  target       category
0  From: degroff@netcom.com (21012d)\nSubject: Re...       2      sci.space
1  From: ab@nova.cc.purdue.edu (Allen B)\nSubject...       1  comp.graphics
2  From: healta@saturn.wwc.edu (Tammy R Healy)\nS...       0    alt.atheism
3  From: capelli@vnet.IBM.COM (Ron Capelli)\nSubj...       1  comp.graphics
4  From: henry@zoo.toronto.edu (Henry Spencer)\nS...       2      sci.space

In [ ]:
df.shape

(1657, 3)

In [ ]:
df.dropna(inplace=True)
df.isnull().sum()

text        0
target      0
category    0
dtype: int64

In [ ]:
text_col = df['text']
text_col

0       From: degroff@netcom.com (21012d)\nSubject: Re...
1       From: ab@nova.cc.purdue.edu (Allen B)\nSubject...
2       From: healta@saturn.wwc.edu (Tammy R Healy)\nS...
3       From: capelli@vnet.IBM.COM (Ron Capelli)\nSubj...
4       From: henry@zoo.toronto.edu (Henry Spencer)\nS...
                              ...                        
1652    From: ab@nova.cc.purdue.edu (Allen B)\nSubject...
1653    From: renes@ecpdsharmony.cern.ch (Rene S. Dutc...
1654    From: xrcjd@resolve.gsfc.nasa.gov (Charles J. ...
1655    From: dietz@cs.rochester.edu (Paul Dietz)\nSub...
1656    From: jhwitten@cs.ruu.nl (Jurriaan Wittenberg)...
Name: text, Length: 1657, dtype: object

In [ ]:
vectorizer = CountVectorizer()

In [ ]:
text_col_transformed = vectorizer.fit_transform(text_col)

In [ ]:
text_col_transformed

<Compressed Sparse Row sparse matrix of dtype 'int64'
	with 255224 stored elements and shape (1657, 29663)>

In [ ]:
print(text_col_transformed.toarray())

[[0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 ...
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]]


In [ ]:
text_col_transformed = text_col_transformed.toarray()
X_train = text_col_transformed
y_train = df['target']

In [ ]:
X_train

array([[0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       ...,
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0]])

In [ ]:
model = MultinomialNB()
model.fit(X_train, y_train)

MultinomialNB()

In [ ]:
y_predict = model.predict(X_train)

In [ ]:
accuracy_score = accuracy_score(y_train, y_predict)
print(accuracy_score)

0.9981894990947495


In [ ]:
classification_report = classification_report(y_train, y_predict)
print(classification_report)

              precision    recall  f1-score   support

           0       1.00      1.00      1.00       480
           1       1.00      1.00      1.00       584
           2       1.00      1.00      1.00       593

    accuracy                           1.00      1657
   macro avg       1.00      1.00      1.00      1657
weighted avg       1.00      1.00      1.00      1657

